services:
  rss-home-lib:
    build:
      context: .
    ports:
      - 4000:4000
    networks:
      - rsschool
    environment:
      NODE_ENV: production
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
    develop:
      watch: 
        - path: ./src
          action: rebuild
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - rsschool
    volumes:
      - postgres:/var/lib/postgresql/data
networks:
  rsschool:
    driver: bridge
volumes:
  postgres: