services:
  rss-home-lib:
    build:
      context: .
    ports:
      - 4000:4000
    networks:
      - rsschool
    environment:
      NODE_ENV: production
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rootdb
    ports:
      - 5432:5432
    networks:
      - rsschool
    volumes:
      - postgres:/var/lib/postgresql/data
networks:
  rsschool:
    # name: rsschool
    driver: bridge
volumes:
  postgres: